// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:881316631246:web:0db804f8c69661e02f369f',
    messagingSenderId: '881316631246',
    projectId: 'mojar-gonit-4f18a',
    authDomain: 'mojar-gonit-4f18a.firebaseapp.com',
    storageBucket: 'mojar-gonit-4f18a.firebasestorage.app',
    measurementId: 'G-YY12ZWVBW5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs2za-MV3yCqYyW6ADlRja7FcnMCV4M_U',
    appId: '1:881316631246:android:155ef356829d9cb72f369f',
    messagingSenderId: '881316631246',
    projectId: 'mojar-gonit-4f18a',
    storageBucket: 'mojar-gonit-4f18a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx6jD9uTwvln-0pGrCBt8NduKpLThdqwg',
    appId: '1:881316631246:ios:f05fdba06a5f7f602f369f',
    messagingSenderId: '881316631246',
    projectId: 'mojar-gonit-4f18a',
    storageBucket: 'mojar-gonit-4f18a.firebasestorage.app',
    iosBundleId: 'com.example.rocketMath',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx6jD9uTwvln-0pGrCBt8NduKpLThdqwg',
    appId: '1:881316631246:ios:f05fdba06a5f7f602f369f',
    messagingSenderId: '881316631246',
    projectId: 'mojar-gonit-4f18a',
    storageBucket: 'mojar-gonit-4f18a.firebasestorage.app',
    iosBundleId: 'com.example.rocketMath',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOVsMOhJN7OD_OTw2dykaiVrrYyWIbIyE',
    appId: '1:881316631246:web:275f56918e1ecdd92f369f',
    messagingSenderId: '881316631246',
    projectId: 'mojar-gonit-4f18a',
    authDomain: 'mojar-gonit-4f18a.firebaseapp.com',
    storageBucket: 'mojar-gonit-4f18a.firebasestorage.app',
    measurementId: 'G-WMJLZ912WR',
  );
}
